global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'bot'
    static_configs:
      - targets: ['bot:9000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
